// Generated by CoffeeScript 1.6.3
/*
Any live cell with fewer than two live neighbours dies, as if caused by under-population.
Any live cell with two or three live neighbours lives on to the next generation.
Any live cell with more than three live neighbours dies, as if by overcrowding.
Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.
*/


(function() {
  var Cell,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.Core = (function() {
    Core.prototype.width = 0;

    Core.prototype.height = 0;

    Core.prototype.total = 300;

    Core.prototype.born = 3;

    Core.prototype.alive = [2, 3];

    Core.prototype.cells = null;

    function Core(size, total) {
      var cell, each, i, _i, _j, _len, _ref, _ref1;
      this.total = total != null ? total : this.total;
      this.width = size.x;
      this.height = size.y;
      this.cells = [];
      for (i = _i = 0, _ref = this.total - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        cell = new Cell;
        cell.randomize(this.width, this.height);
        _ref1 = this.cells;
        for (_j = 0, _len = _ref1.length; _j < _len; _j++) {
          each = _ref1[_j];
          if (cell.x === each.x && cell.y === each.y) {
            cell.randomize(this.width, this.height);
          }
        }
        this.cells.push(cell);
      }
    }

    Core.prototype.addCell = function(pos) {
      var cell, test, _i, _len, _ref;
      _ref = this.cells;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cell = _ref[_i];
        if (cell.x === pos.x && cell.y === pos.y) {
          test = true;
        }
      }
      if (!test) {
        return this.cells[this.cells.length] = new Cell(pos.x, pos.y);
      }
    };

    Core.prototype.update = function() {
      var cell, count, i, index, indexes, j, _i, _j, _k, _l, _len, _len1, _ref, _results;
      indexes = [];
      _ref = this.cells;
      for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
        cell = _ref[index];
        count = 0;
        for (i = _j = -1; _j <= 1; i = ++_j) {
          for (j = _k = -1; _k <= 1; j = ++_k) {
            if ((i !== j) && this._isAlive(cell.x + i, cell.y + j)) {
              count++;
            } else {
              this._deadUpdate({
                x: cell.x + i,
                y: cell.y + j
              });
            }
          }
        }
        if (__indexOf.call(this.alive, count) < 0) {
          indexes[indexes.length] = index;
        }
      }
      _results = [];
      for (_l = 0, _len1 = indexes.length; _l < _len1; _l++) {
        index = indexes[_l];
        _results.push(this.cells.splice(index, 1));
      }
      return _results;
    };

    Core.prototype._deadUpdate = function(cell) {
      var count, i, j, _i, _j;
      count = 0;
      for (i = _i = -1; _i <= 1; i = ++_i) {
        for (j = _j = -1; _j <= 1; j = ++_j) {
          if ((i !== j) && this._isAlive(cell.x + i, cell.y + j)) {
            count++;
          }
        }
      }
      if (count === this.born) {
        console.log('aaa');
        return this.cells[this.cells.length] = new Cell(cell.x, cell.y);
      }
    };

    Core.prototype._isAlive = function(x, y) {
      var cell, _i, _len, _ref;
      _ref = this.cells;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cell = _ref[_i];
        if (cell.x === x && cell.y === y) {
          return true;
        }
      }
      return false;
    };

    return Core;

  })();

  Cell = (function() {
    Cell.prototype.x = 0;

    Cell.prototype.y = 0;

    function Cell(x, y) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
    }

    Cell.prototype.randomize = function(maxWidth, maxHeight) {
      this.x = ~~(Math.random() * maxWidth);
      this.y = ~~(Math.random() * maxHeight);
      return {
        x: this.x,
        y: this.y
      };
    };

    return Cell;

  })();

  window.Core = Core;

}).call(this);
